title: Graham Greene # your name (or website title) here
logo: "images/LinkedIn Profile Photo.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Chemical Engineering graduate pursuing opportunities in Data Science. Eager to tackle complex problems in a continuous learning environment.
  <br><br>
  <a href="https://www.linkedin.com/in/grahamdsgreene/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Google Analytics
google_analytics: G-MMNPLZRHWH # your Google Analytics tracking ID here
