project:
  type: website
  output-dir: docs

website:
  title: "Graham Greene"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects       

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true



